[package]
name = "picodox-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {
  version = "1.0",
  default-features = false,
  features = ["derive"],
}

[dev-dependencies]
postcard = "1.0"
