[package]
name = "picodox-firmware"
version = "0.1.0"
edition = "2021"

[dependencies]
circular-buffer = { version = "0.1.9", default-features = false }
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
embedded-hal = "1.0.0"
heapless = "0.8.0"
panic-halt = "1.0.0"
rp-pico = "0.9.0"
usb-device = "0.3.2"
usbd-serial = "0.2.2"
