compile:
  cargo build
  elf2uf2-rs target/thumbv6m-none-eabi/debug/picodox-firmware target/thumbv6m-none-eabi/debug/picodox-firmware.uf2

flash:
  -cd ../cli && cargo run flash
  cargo build
  picotool load -x -t elf target/thumbv6m-none-eabi/debug/picodox-firmware

log:
  socat -u /dev/ttyACM1,rawer STDOUT | defmt-print -e target/thumbv6m-none-eabi/debug/picodox-firmware
